# See https://github.com/crate-ci/typos/blob/master/docs/reference.md to configure typos

[files]
extend-exclude = [
    "third_party/snowball/**"
]

<<<<<<< HEAD
[default]
extend-ignore-re = [
    "grea.*",
    "Grea.*",
]
=======
[default.extend-words]
Fo = "Fo"
InFo = "InFo"
SeArCh = "SeArCh" 
CrEaTe = "CrEaTe"
LiSt = "LiSt"
DeBuG = "DeBuG"
DrOpInDeX = "DrOpInDeX"
>>>>>>> upstream/main

[type.cpp]
extend-ignore-re = [
    "baNAna",
    "eXIst"
]
